Trigger CI/CD

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -63,7 +63,10 @@ jobs:
       - name: Save EC2 Public IP
         id: ec2_output
         run: |
-          EC2_IP=$(terraform output -raw ec2_public_ip 2>/dev/null | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
+          EC2_IP=$(terraform output -raw ec2_public_ip | tr -d '\n')
+          if [[ -z "$EC2_IP" ]]; then
+            echo "EC2 public IP not found"; exit 1
+          fi
           echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV
 
   app_deploy:
